# Generated by Django 2.1.3 on 2018-11-20 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_number', models.DecimalField(decimal_places=0, max_digits=8)),
                ('cash_float', models.DecimalField(decimal_places=2, max_digits=6)),
                ('liters_float', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_number', models.DecimalField(decimal_places=0, max_digits=8)),
                ('cash_float', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note_text', models.CharField(max_length=256, null=True)),
                ('title_text', models.CharField(max_length=32)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='refueling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Fueling'),
        ),
        migrations.AddField(
            model_name='car',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Service'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
