# Generated by Django 2.1.3 on 2018-11-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='refueling',
        ),
        migrations.AddField(
            model_name='car',
            name='refueling',
            field=models.ManyToManyField(to='Site.Fueling'),
        ),
    ]
