# Generated by Django 2.1.3 on 2018-11-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20181120_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='services',
        ),
        migrations.AddField(
            model_name='car',
            name='services',
            field=models.ManyToManyField(to='Site.Service'),
        ),
    ]
