# Generated by Django 2.1.3 on 2018-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20181121_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='buy_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_float',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_number',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='production_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='registration_text',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vin_text',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
